## Pandas and CSV/EXCEL

#### Libraries - Imports

In [1]:
# pip install pandas

In [2]:
 # This is a convention in Python community.

In [3]:
import os
import pandas as pd #conventional

#### Read

Download the csv of [Roman Amphitheaters](https://github.com/roman-amphitheaters/roman-amphitheaters/blob/main/roman-amphitheaters.csv)

In [4]:
 # df stands for dataframe, i.e., row and columns of data.

In [5]:
df = pd.read_csv("roman-amphitheaters.csv")

In [6]:
# df

In [7]:
df.head(10) #first x rows
df.tail(5) # last x rows

,id,title,label,latintoponym,pleiades,welchid,golvinid,buildingtype,chronogroup,secondcentury,...,amphitheatrum,dimensionsunknown,arenamajor,arenaminor,extmajor,extminor,exteriorheight,longitude,latitude,elevation
270,saintGeorgesDuBoisAmphitheater,Amphitheater at Saint-Georges-du-Bois,Saint-Georges-du-Bois,NaN,NaN,NaN,103.0,amphitheater,first-century,True,...,https://amphi-theatrum.de/1529.html,False,54.0,30.0,65.0,50.0,NaN,-0.749919,46.142723,39
271,toledoAmphitheater,Amphitheater at Toledo,Toledo,Toletum,https://pleiades.stoa.org/places/266066,NaN,NaN,amphitheater,imperial,True,...,https://amphi-theatrum.de/3090.html,True,NaN,NaN,NaN,NaN,NaN,-4.022888,39.865349,482
272,kaiseraugustAmphitheater,Amphitheater at Kaiseraugst,Kaiseraugst,Castrum Rauracense,https://pleiades.stoa.org/places/81716458,NaN,NaN,amphitheater,fourth-century,False,...,https://amphi-theatrum.de/3066.html,False,NaN,NaN,50.0,40.0,NaN,7.721596,47.540822,482
273,ammaiaAmphitheater,Amphitheater at Ammaia,Ammaia,Ammaia,https://pleiades.stoa.org/places/255975,NaN,NaN,amphitheater,imperial,True,...,https://amphi-theatrum.de/3020.html,False,NaN,NaN,60.0,NaN,NaN,-7.391970,39.369905,566
274,contributaAmphitheater,Amphitheater at Contributa Iulia Ugultunia,Contributa,Contributa Iulia Ugultunia,https://pleiades.stoa.org/places/256126,NaN,NaN,amphitheater,imperial,True,...,https://amphi-theatrum.de/3093.html,False,NaN,NaN,72.0,NaN,NaN,-6.389320,38.347751,501

#### Data types in our csv

In [8]:
df.shape # notice that this is an attribute so no parentheses

(275, 24)

In [9]:
df.info() # notice that this is a method, so we need parentheses

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 275 non-null    object
 1   title              275 non-null    object
 2   label              275 non-null    object
 3   latintoponym       261 non-null    object
 4   pleiades           274 non-null    object
 5   welchid            19 non-null     float64
 6   golvinid           166 non-null    float64
 7   buildingtype       275 non-null    object
 8   chronogroup        275 non-null    object
 9   secondcentury      275 non-null    bool
 10  capacity           153 non-null    float64
 11  modcountry         275 non-null    object
 12  romanregion        274 non-null    object
 13  zotero             56 non-null     object
 14  amphitheatrum      239 non-null    object
 15  dimensionsunknown  275 non-null    bool
 16  arenamajor         184 non-null    float64
 17  arenaminor         179 non-null    float64
 18  extmajor           219 non-null    float64
 19  extminor           198 non-null    float64
 20  exteriorheight     3 non-null      float64
 21  longitude          275 non-null    float64
 22  latitude           275 non-null    float64
 23  elevation          275 non-null    int64
dtypes: bool(2), float64(10), int64(1), object(11)
memory usage: 47.9+ KB

In [10]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### Example: Shipwrecks Database

Download the [Shipwrecks Database](http://oxrep.classics.ox.ac.uk/docs/StraussShipwrecks.zip) for the [The Oxford Roman Economy Project](http://oxrep.classics.ox.ac.uk/).

In [11]:
df = pd.read_excel("StraussShipwrecks.xlsx")

In [12]:
df.head(1)

   Wreck ID  Strauss ID    Name Parker Number  Sea area  Country      Region  Latitude  Longitude  Min depth  Max depth Depth          Period       Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks Marble type Other cargo Hull remains Shipboard paraphernalia Ship equipment  Estimated tonnage Amphora type
0         1         331  Komiza           NaN  Adriatic  Croatia  Vis Island  43.03333   16.08333       30.0       30.0   30m  Roman Imperial  C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN           Egypt       Northern Italy  M. Jurišić, Ancient Shipwrecks of the Adriatic...  Completely looted site with sherds of Egyptian...      True   False        False       False   False         NaN         NaN          NaN                     NaN            NaN                NaN          NaN

#### Access one column

In [13]:
df['Sea area']

0       Adriatic
1       Adriatic
2       Adriatic
3       Adriatic
4       Adriatic
          ...
1779         NaN
1780         NaN
1781         NaN
1782         NaN
1783         NaN
Name: Sea area, Length: 1784, dtype: object

#### What datatype is this?

In [14]:
type(df['Sea area'])

pandas.core.series.Series

#### Access two columns

In [15]:
df[['Name','Sea area']]

                                Name  Sea area
0                             Komiza  Adriatic
1                            Lokunji  Adriatic
2                       Maharac Cape  Adriatic
3                               Mlin  Adriatic
4                           Plavac B  Adriatic
...                              ...       ...
1779              Olbia Late Roman 2       NaN
1780                  Olbia medieval       NaN
1781  Isola della Gallinara (Savona)       NaN
1782                San Vito Lo Capo       NaN
1783   Capo Colonna and Capo Alfieri       NaN

[1784 rows x 2 columns]

In [16]:
# access three columns
df[['Wreck ID','Name','Sea area']]

      Wreck ID                            Name  Sea area
0            1                          Komiza  Adriatic
1            2                         Lokunji  Adriatic
2            3                    Maharac Cape  Adriatic
3            4                            Mlin  Adriatic
4            5                        Plavac B  Adriatic
...        ...                             ...       ...
1779      9058              Olbia Late Roman 2       NaN
1780      9059                  Olbia medieval       NaN
1781      9060  Isola della Gallinara (Savona)       NaN
1782      9061                San Vito Lo Capo       NaN
1783      9063   Capo Colonna and Capo Alfieri       NaN

[1784 rows x 3 columns]

Check [here](https://www.w3schools.com/python/pandas/pandas_series.asp).

#### What datatype is this now?

In [17]:
type(df[['Name','Sea area']])

pandas.core.frame.DataFrame

#### Get all columns

In [18]:
df.head(1)

   Wreck ID  Strauss ID    Name Parker Number  Sea area  Country      Region  Latitude  Longitude  Min depth  Max depth Depth          Period       Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks Marble type Other cargo Hull remains Shipboard paraphernalia Ship equipment  Estimated tonnage Amphora type
0         1         331  Komiza           NaN  Adriatic  Croatia  Vis Island  43.03333   16.08333       30.0       30.0   30m  Roman Imperial  C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN           Egypt       Northern Italy  M. Jurišić, Ancient Shipwrecks of the Adriatic...  Completely looted site with sherds of Egyptian...      True   False        False       False   False         NaN         NaN          NaN                     NaN            NaN                NaN          NaN

### Get all rows
- iloc (integer location)
- loc

### 1) iloc

In [19]:
df.iloc[0] #gives the first row

Wreck ID                                                                   1
Strauss ID                                                               331
Name                                                                  Komiza
Parker Number                                                            NaN
Sea area                                                            Adriatic
Country                                                              Croatia
Region                                                            Vis Island
Latitude                                                            43.03333
Longitude                                                           16.08333
Min depth                                                               30.0
Max depth                                                               30.0
Depth                                                                    30m
Period                                                        Roman Imperial
Dating                                                           C1st-2nd AD
Earliest date                                                            1.0
Latest date                                                            200.0
Date range                                                               NaN
Mid point of date range                                                  NaN
Probability                                                              NaN
Place of origin                                                        Egypt
Place of destination                                          Northern Italy
Reference                  M. Jurišić, Ancient Shipwrecks of the Adriatic...
Comments                   Completely looted site with sherds of Egyptian...
Amphorae                                                                True
Marble                                                                 False
Columns etc                                                            False
Sarcophagi                                                             False
Blocks                                                                 False
Marble type                                                              NaN
Other cargo                                                              NaN
Hull remains                                                             NaN
Shipboard paraphernalia                                                  NaN
Ship equipment                                                           NaN
Estimated tonnage                                                        NaN
Amphora type                                                             NaN
Name: 0, dtype: object

#### How can we get the first two rows?

In [20]:
df.iloc[0:2] #gets the first two rows

   Wreck ID  Strauss ID     Name Parker Number  Sea area  Country          Region  Latitude  Longitude  Min depth  Max depth Depth          Period       Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks Marble type Other cargo Hull remains Shipboard paraphernalia Ship equipment  Estimated tonnage Amphora type
0         1         331   Komiza           NaN  Adriatic  Croatia      Vis Island  43.03333   16.08333       30.0       30.0   30m  Roman Imperial  C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN           Egypt       Northern Italy  M. Jurišić, Ancient Shipwrecks of the Adriatic...  Completely looted site with sherds of Egyptian...      True   False        False       False   False         NaN         NaN          NaN                     NaN            NaN                NaN          NaN
1         2         328  Lokunji           NaN  Adriatic  Croatia  Kvarner region  44.70000   14.28333        4.0       12.0   12m  Roman Imperial     C 1st AD            1.0        100.0         NaN                      NaN          NaN             Cos       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...                                                NaN      True   False        False       False   False         NaN         NaN          NaN                     NaN            NaN                NaN          NaN

#### How can we get the first column of the above df?

In [21]:
df.iloc[0:2]['Sea area'] #gets the "Sea Area" for the first two rows

0    Adriatic
1    Adriatic
Name: Sea area, dtype: object

### 2) loc
In this way, we do not get the first, second, etc., row. We get the row that has the index we specify.

In [22]:
df.loc[15] #gets the 15th row

Wreck ID                                                                  16
Strauss ID                                                               503
Name                                                                  Tyre F
Parker Number                                                           1189
Sea area                                               Eastern Mediterranean
Country                                                              Lebanon
Region                                             On the south side of Tyre
Latitude                                                                 NaN
Longitude                                                                NaN
Min depth                                                                NaN
Max depth                                                                NaN
Depth                                                                Shallow
Period                                                    Hellenistic/ Roman
Dating                                                          C 3rd-2nd BC
Earliest date                                                         -200.0
Latest date                                                           -100.0
Date range                                                               NaN
Mid point of date range                                                  NaN
Probability                                                              NaN
Place of origin                                                            ?
Place of destination                                                       ?
Reference                  Summary reports, R. Marx, IJNA 3 (1974), 332; ...
Comments                   Presumably amphorae were found at this looted ...
Amphorae                                                                True
Marble                                                                 False
Columns etc                                                            False
Sarcophagi                                                             False
Blocks                                                                 False
Marble type                                                              NaN
Other cargo                                                              NaN
Hull remains                                                             NaN
Shipboard paraphernalia                                                  NaN
Ship equipment                                                           NaN
Estimated tonnage                                                        NaN
Amphora type                                                             NaN
Name: 15, dtype: object

### Let's grab some data

#### Get the Country column

In [23]:
df['Country'] #gets the entire country column

0       Croatia
1       Croatia
2       Croatia
3       Croatia
4       Croatia
         ...
1779      Italy
1780      Italy
1781      Italy
1782      Italy
1783      Italy
Name: Country, Length: 1784, dtype: object

#### Count with `.value_counts()`

In [24]:
df['Country'].value_counts() #counts unique appearances of each value

Italy                   247
France                  217
Greece                   94
ZZ-Non-Mediterranean     69
Croatia                  63
Turkey                   62
Israel                   56
Spain                    30
Bulgaria                 18
Cyprus                   13
Albania                  11
International waters      9
Libya                     6
Lebanon                   5
Egypt                     5
Tunisia                   2
Montenegro                2
India                     1
Romania                   1
Minorca                   1
Syria                     1
Italy - Sicily            1
Malta                     1
Sudan                     1
Name: Country, dtype: int64

### Set index `.set_index()`

In [25]:
#sorts by a certain argument - assigns that argument to be the index -- 
# ("index" is the name of the internally assigned numeration)
df.set_index('Country')

         Wreck ID  Strauss ID                            Name Parker Number  Sea area                           Region  Latitude  Longitude  Min depth  Max depth    Depth          Period         Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks Marble type                                        Other cargo          Hull remains Shipboard paraphernalia                                     Ship equipment  Estimated tonnage Amphora type
Country
Croatia         1         331                          Komiza           NaN  Adriatic                       Vis Island  43.03333   16.08333       30.0       30.0      30m  Roman Imperial    C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN           Egypt       Northern Italy  M. Jurišić, Ancient Shipwrecks of the Adriatic...  Completely looted site with sherds of Egyptian...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                NaN          NaN
Croatia         2         328                         Lokunji           NaN  Adriatic                   Kvarner region  44.70000   14.28333        4.0       12.0      12m  Roman Imperial       C 1st AD            1.0        100.0         NaN                      NaN          NaN             Cos       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...                                                NaN      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                NaN          NaN
Croatia         3         329                    Maharac Cape           NaN  Adriatic                     Mljet island  42.73333   17.66666        3.0       20.0    3-20m  Roman Imperial       C 1st AD            1.0        100.0         NaN                      NaN          NaN          Rhodes       Northern Italy  D. Vrsalović, PhD thesis (unpublished; 1979), ...                                                NaN      True   False        False       False   False         NaN  Eastern coarse ware pottery of biconical dishe...                   NaN                     NaN                                                NaN                NaN          NaN
Croatia         4         330                            Mlin           702  Adriatic                    Split channel  43.45000   16.23333       25.0       40.0      40m  Roman Imperial   C 1st-2nd AD            1.0        200.0         NaN                      NaN          NaN          Aegean       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...  A heavily looted mixed cargo of Greek amphorae...      True   False        False       False   False         NaN                                                NaN  Remains of the hull.                     NaN  Two lead anchor stocks, though possibly not fr...                NaN          NaN
Croatia         5         322                        Plavac B           832  Adriatic  Zlarin Island, central Dalmatia       NaN        NaN        NaN        NaN      NaN  Roman Imperial        C1st AD            1.0        100.0         NaN                      NaN          NaN             NaN                  NaN                                                NaN                                                NaN     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                  .                NaN          NaN
...           ...         ...                             ...           ...       ...                              ...       ...        ...        ...        ...      ...             ...            ...            ...          ...         ...                      ...          ...             ...                  ...                                                ...                                                ...       ...     ...          ...         ...     ...         ...                                                ...                   ...                     ...                                                ...                ...          ...
Italy        9058           0              Olbia Late Roman 2           NaN       NaN                         Sardinia  40.91148    9.50738        0.0        0.0       0m      Late Roman        C5th AD          400.0        500.0         0.0                      0.0          0.0             NaN                  NaN  R. D'Oriano, Archeologia in Sardegna, 2007,  9...  Three other C5th AD wrecks found during constr...     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
Italy        9059           0                  Olbia medieval           NaN       NaN                         Sardinia  40.91148    9.50738        0.0        0.0       0m        Medieval  C11th-15th AD         1000.0       1500.0         0.0                      0.0          0.0             NaN                  NaN  R. D'Oriano, Archeologia in Sardegna, 2007,  9...  Five small wrecks from the eleventh, fourteent...     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
Italy        9060           0  Isola della Gallinara (Savona)           NaN       NaN                          Liguria  44.02648    8.22996       50.0       50.0      50m  Roman Republic        C1st BC         -100.0         -1.0         0.0                      0.0          0.0        Campania                  NaN  http://www.archeosub.it/news2003/news0311.htm#...  A mound of intact Dr 1 amphorae and 'other car...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
Italy        9061           0                San Vito Lo Capo           NaN       NaN                           Sicily  38.18825   12.74551        0.0        0.0      NaN          Norman       C12th AD         1100.0       1200.0         0.0                      0.0          0.0             NaN                  NaN  F. Faccenna, Il Relitto di San Vito Lo Capo (2...  A local Sicilian ship carrying amphorae and ja...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
Italy        9063           0   Capo Colonna and Capo Alfieri           NaN       NaN                         Calabria  38.95399   17.17163        0.0        0.0  shallow      Late Roman    C4th-5th AD          300.0        500.0         0.0                      0.0          0.0             NaN                  NaN  http://www.archeomar.it/templates/archeomar/at...       A probable Late Roman shipwreck of amphorae.      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN

[1784 rows x 34 columns]

#### Did the original dataframe change?

In [26]:
# no
# df

#### let's put the parameter `inplace=True`

In [27]:
df.set_index('Country', inplace=True)

#### What will happen of I look for `df.loc[0]`?

In [28]:
# gives an error - #there is no more index with 1
# df.loc[0]

#### Let's reset the index

In [29]:
df.reset_index(inplace = True)

In [30]:
# df

### Sort `.sort_index(ascending=False)`

In [31]:
df.sort_index(ascending=False)

      Country  Wreck ID  Strauss ID                            Name Parker Number  Sea area                           Region  Latitude  Longitude  Min depth  Max depth    Depth          Period         Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks Marble type                                        Other cargo          Hull remains Shipboard paraphernalia                                     Ship equipment  Estimated tonnage Amphora type
1783    Italy      9063           0   Capo Colonna and Capo Alfieri           NaN       NaN                         Calabria  38.95399   17.17163        0.0        0.0  shallow      Late Roman    C4th-5th AD          300.0        500.0         0.0                      0.0          0.0             NaN                  NaN  http://www.archeomar.it/templates/archeomar/at...       A probable Late Roman shipwreck of amphorae.      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1782    Italy      9061           0                San Vito Lo Capo           NaN       NaN                           Sicily  38.18825   12.74551        0.0        0.0      NaN          Norman       C12th AD         1100.0       1200.0         0.0                      0.0          0.0             NaN                  NaN  F. Faccenna, Il Relitto di San Vito Lo Capo (2...  A local Sicilian ship carrying amphorae and ja...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1781    Italy      9060           0  Isola della Gallinara (Savona)           NaN       NaN                          Liguria  44.02648    8.22996       50.0       50.0      50m  Roman Republic        C1st BC         -100.0         -1.0         0.0                      0.0          0.0        Campania                  NaN  http://www.archeosub.it/news2003/news0311.htm#...  A mound of intact Dr 1 amphorae and 'other car...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1780    Italy      9059           0                  Olbia medieval           NaN       NaN                         Sardinia  40.91148    9.50738        0.0        0.0       0m        Medieval  C11th-15th AD         1000.0       1500.0         0.0                      0.0          0.0             NaN                  NaN  R. D'Oriano, Archeologia in Sardegna, 2007,  9...  Five small wrecks from the eleventh, fourteent...     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1779    Italy      9058           0              Olbia Late Roman 2           NaN       NaN                         Sardinia  40.91148    9.50738        0.0        0.0       0m      Late Roman        C5th AD          400.0        500.0         0.0                      0.0          0.0             NaN                  NaN  R. D'Oriano, Archeologia in Sardegna, 2007,  9...  Three other C5th AD wrecks found during constr...     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
...       ...       ...         ...                             ...           ...       ...                              ...       ...        ...        ...        ...      ...             ...            ...            ...          ...         ...                      ...          ...             ...                  ...                                                ...                                                ...       ...     ...          ...         ...     ...         ...                                                ...                   ...                     ...                                                ...                ...          ...
4     Croatia         5         322                        Plavac B           832  Adriatic  Zlarin Island, central Dalmatia       NaN        NaN        NaN        NaN      NaN  Roman Imperial        C1st AD            1.0        100.0         NaN                      NaN          NaN             NaN                  NaN                                                NaN                                                NaN     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                  .                NaN          NaN
3     Croatia         4         330                            Mlin           702  Adriatic                    Split channel  43.45000   16.23333       25.0       40.0      40m  Roman Imperial   C 1st-2nd AD            1.0        200.0         NaN                      NaN          NaN          Aegean       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...  A heavily looted mixed cargo of Greek amphorae...      True   False        False       False   False         NaN                                                NaN  Remains of the hull.                     NaN  Two lead anchor stocks, though possibly not fr...                NaN          NaN
2     Croatia         3         329                    Maharac Cape           NaN  Adriatic                     Mljet island  42.73333   17.66666        3.0       20.0    3-20m  Roman Imperial       C 1st AD            1.0        100.0         NaN                      NaN          NaN          Rhodes       Northern Italy  D. Vrsalović, PhD thesis (unpublished; 1979), ...                                                NaN      True   False        False       False   False         NaN  Eastern coarse ware pottery of biconical dishe...                   NaN                     NaN                                                NaN                NaN          NaN
1     Croatia         2         328                         Lokunji           NaN  Adriatic                   Kvarner region  44.70000   14.28333        4.0       12.0      12m  Roman Imperial       C 1st AD            1.0        100.0         NaN                      NaN          NaN             Cos       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...                                                NaN      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                NaN          NaN
0     Croatia         1         331                          Komiza           NaN  Adriatic                       Vis Island  43.03333   16.08333       30.0       30.0      30m  Roman Imperial    C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN           Egypt       Northern Italy  M. Jurišić, Ancient Shipwrecks of the Adriatic...  Completely looted site with sherds of Egyptian...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                NaN          NaN

[1784 rows x 35 columns]

In [32]:
# because no inplace = true , this doesn't change the dataframe. Just changes the way one is looking at it

## Filter

#### what's the result of the below statement?

In [33]:
df['Country'] == 'Greece' #the filter returns every row's value at this variable

0       False
1       False
2       False
3       False
4       False
        ...
1779    False
1780    False
1781    False
1782    False
1783    False
Name: Country, Length: 1784, dtype: bool

In [34]:
df[(df['Country'] == 'Greece')] #filters for Greece

     Country  Wreck ID  Strauss ID                           Name Parker Number               Sea area                                  Region  Latitude  Longitude  Min depth  Max depth                               Depth                   Period                      Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability                      Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks                                        Marble type                                        Other cargo                                       Hull remains                            Shipboard paraphernalia                                     Ship equipment  Estimated tonnage Amphora type
14    Greece        15          72           Aghios Eustratios(?)           NaN                 Aegean               Between Euboea and Lesbos       NaN        NaN        NaN        NaN                           Not known     early Roman Imperial              End of C1st BC          -25.0         -1.0         NaN                      NaN          NaN                               Aegean                    ?                         National Museum of Athens.                                                NaN     False   False        False       False   False                                                NaN  Bronze statue of Augustus riding a horse.Tthis...                                                NaN                                                NaN                                                NaN                NaN          NaN
41    Greece        42          30                         Piadha           810                 Aegean             North of Epidaurus, Argolis       NaN        NaN       30.0       35.0                              30-35m        Hellenistic/Roman                C 5th-1st BC         -500.0         -1.0         NaN                      NaN          NaN                               Aegean                    ?  G. Papathanassopoulos, IJNA 9 (1980), 164-67; ...                                                NaN     False   False        False       False   False                                                NaN                                     Laconian tiles                                                NaN                                                NaN                                                NaN                NaN          NaN
42    Greece        43         300                      Preveza B           905  Central Mediterranean                   In the area of Actium       NaN        NaN        NaN        NaN                           Not known        Hellenistic/Roman                  300-250 BC         -300.0       -250.0         NaN                      NaN          NaN                              Corinth               Italy?  G. Kapitän, IJNA 2 (1973), 185-6; C. Koehler, ...  Corinthian A and B forms, now in the British M...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
43    Greece        44         305                      Methone A           693  Central Mediterranean               Near Methone, Peloponnese       NaN        NaN        NaN        NaN                             Shallow             Hellenistic?                Hellenistic?         -425.0        -25.0         NaN                      NaN          NaN                              Aegean?               Italy?  P. Throckmorton and J. Bullitt, Expedition 5 (...  A badly broken-up wreck, presumably with ampho...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
44    Greece        45          31                       Marathon           650                 Aegean                   Near Marathon, Attica       NaN        NaN        NaN        NaN                           Not known        Hellenistic/Roman                C 4th-1st BC         -400.0         -1.0         NaN                      NaN          NaN                               Athens                    ?  K. Rhomaios, Arkhailogikon Deltion 9 (1924-5),...                                                NaN     False   False        False       False   False                                                NaN  Famous bronze statue of a boy, perhaps the god...                                    Wood fragments.                                                NaN                                                NaN                NaN          NaN
45    Greece        46         306                      Preveza A           904  Central Mediterranean                             Near Actium       NaN        NaN        NaN        NaN                                 18m        Hellenistic/Roman                  200-150 BC         -200.0       -150.0         NaN                      NaN          NaN                                Italy                    ?  Brief report only,  I. Vokotopoulou, Arkhailog...  Graeco-Italic, perhaps Will Type D. Large numbers      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
46    Greece        47          33                         Dhrapi           363                 Aegean  Between Hydra and Spetsai, Peloponnese       NaN        NaN        NaN        NaN                              35-40m        Hellenistic/Roman                   250-50 BC         -250.0        -50.0         NaN                      NaN          NaN                               Rhodes                    ?  G. Papathanassopoulos, IJNA 9 (1980), 164-67; ...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                 Lead anchor stock.                NaN          NaN
47    Greece        48          34                     Artemision            57                 Aegean                         Northern Euboea       NaN        NaN        NaN        NaN                              35-40m        Hellenistic/Roman                   200-80 BC         -200.0        -80.0         NaN                      NaN          NaN                             Corinth?            Pergamum?  V. Kallipolitis, Athens Annals of Archaeology ...                                                NaN     False   False        False       False   False                                                NaN  Bronze works of art, including C5th male statu...                               Timbers lie in situ.                                      Stone pestle.             Lead anchor stock and grinding stones.                NaN          NaN
48    Greece        49         307                         Limeni           597  Central Mediterranean                  South west Peloponnese       NaN        NaN        NaN        NaN                           Not known         Roman Republican              Early C 1st BC         -100.0        -75.0         NaN                      NaN          NaN                                    ?                    ?  G. Touchais, BCH 102 (1978), 678;  Parker (199...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                             A large merchant ship?                                                NaN                                                NaN                NaN          NaN
49    Greece        50          35                       Rhaphina           982                 Aegean                    East coast of Attica       NaN        NaN        NaN        NaN                           Not known         Roman Republican                    C 1st BC         -100.0         -1.0         NaN                      NaN          NaN                                  Cos                    ?  H Hoffman, Ten Centuries that Shaped the West:...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
50    Greece        51         308                      Areopolis            54  Central Mediterranean                       Mani, Peloponnese       NaN        NaN        NaN        NaN                               6-14m         Roman Republican                    C 1st BC         -100.0         -1.0         NaN                      NaN          NaN                             Adriatic               Aegean  F. Frost, Archaeologia 25 (1968), 40-3; Parker...                            Scattered Lamboglia  2.      True   False        False       False   False                                                NaN                                                NaN                               Possibly a 30m ship?                                                NaN                                                NaN                NaN          NaN
51    Greece        52          42                  Ai-Strate (?)           NaN                 Aegean                                  Euboea       NaN        NaN        NaN        NaN                           Not known        Hellenistic/Roman             C3rd BC- 3rd AD         -325.0        400.0         NaN                      NaN          NaN                                    ?                    ?                               AR 38 (1991-92), 33.   Hellenistic and Roman amphoras found in the sea.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
52    Greece        53         313                   Palairos (?)           NaN  Central Mediterranean                                 Aetolia       NaN        NaN        NaN        NaN                           Not known                        ?                     Unknown            1.0        350.0         NaN                      NaN          NaN                             Carystos               Italy?                               AR 47 (2000-01), 43.                                                NaN     False    True         True       False   False  A column of green cipollino 4.10m long and 0.3...                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
68    Greece        69          36                  Antikythera A            44                 Aegean         Off southern tip of Peloponnese       NaN        NaN        NaN        NaN                              50-60m         Roman Republican     80 BC or a little later          -80.0        -70.0         NaN                      NaN          NaN               Alex/ Pergamum/ Aegean                 Rome  Weinberg et al TAPA 55.3 (1965); P. Throckmort...  One of the earliest wrwcks to be excavated in ...      True    True         True       False   False  36 marble statues, many of which are copies of...  Contemporary works of art and old masters from...  Lead-sheathed hull, part of which has been rai...                                                NaN                               Anchors and rigging.                NaN          NaN
69    Greece        70          37                        Kythera           564                 Aegean         Off southern tip of Peloponnese       NaN        NaN        NaN        NaN                              10-15m           Roman Imperial                50 BC-AD 110          -50.0        110.0         NaN                      NaN          NaN                               Rhodes                Rome?  Discovered by P. Throckmorton but unpublished,...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
70    Greece        71         309                      Methone D           696  Central Mediterranean        South west Messinia, Peloponnese       NaN        NaN        NaN        NaN                             Shallow           Roman Imperial              C 2nd -3rd  AD          100.0        300.0         NaN                      NaN          NaN                                Assos               Italy?  P. Throckmorton and J. Bullitt, Expedition 5 (...                                                NaN     False    True        False        True   False  Four unfinished garland sarcophagi of Assos st...            Tiles, pottery and a glass unguent jar.                                                NaN                                                NaN         Small water-worn stones, probably ballast.                NaN          NaN
71    Greece        72          39                      Piraeus A           817                 Aegean                      In Piraeus harbour       NaN        NaN        NaN        NaN                           Not known           Roman Imperial                    C 2nd AD          100.0        200.0         NaN                      NaN          NaN                              Aegean?                    ?  G. Bass Archaeology Underwater (1966), 78; Par...                                                NaN     False   False        False       False   False                                                NaN                         Sculptures of the C2nd AD.  Flat bottomed vessel which had burnt and sunk ...                                                NaN                                                NaN                NaN          NaN
72    Greece        73         310                      Methone C           695  Central Mediterranean        South west Messinia, Peloponnese       NaN        NaN        NaN        NaN                               9-10m           Roman Imperial                  AD 200-250          200.0        250.0         NaN                      NaN          NaN                               Aegean               Italy?  P. Throckmorton and J. Bullitt, Expedition 5 (...                                                NaN      True    True         True       False   False  One complete and twenty fragments of already b...                               A fragment of glass.                                                NaN                                                NaN                                                NaN                NaN          NaN
73    Greece        74         312                   Cape Akritas           201  Central Mediterranean             South Messinia, Peloponnese       NaN        NaN        NaN        NaN                               5-10m                        ?                     Unknown            NaN          NaN         NaN                      NaN          NaN                                    ?                    ?  G. Papathanassopoulos, Arkhailogikon Deltion 2...                     Scattered remains of amphorae.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN  The amphora fragments were found between two b...                NaN          NaN
74    Greece        75          43                  Antikythera B            45                 Aegean             Off south east Peloponnesus       NaN        NaN        NaN        NaN                             Unknown           Roman Imperial            C 1st BC- 5th AD         -100.0        500.0         NaN                      NaN          NaN                               Aegean                Rome?       Dumas Trente Siècles sous La Mer (1972), 71.                     Large amphorae ‘like barrels’.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN  Lead stock and reinforcement collar of an anchor.                NaN          NaN
75    Greece        76         311                      Sapientza          1037  Central Mediterranean        South west Messinia, Peloponnese       NaN        NaN        NaN        NaN                                7-8m                    Roman                       Roman         -150.0        400.0         NaN                      NaN          NaN                               Aegean               Italy?                  Unpublished; Parker (1992), 1037.                                                NaN      True    True        False       False    True  Blocks and slabs of white marble, estimated we...                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
80    Greece        81          57                   Kalymnos (?)           NaN                 Aegean                    Kalymnos, Dodecanese       NaN        NaN        NaN        NaN                          Not known.        Hellenistic/Roman           Hellenistic/Roman         -325.0        400.0         NaN                      NaN          NaN                               Aegean                    ?           Εργον ΥΠΠΟ 2, 152; AR 47 (2000-01), 122.                                                NaN     False   False        False       False   False                                                NaN  Leg of a bronze statue of a horseman, probably...                                                NaN                                                NaN                                                NaN                NaN          NaN

In [35]:
print(type(df[(df['Wreck ID'] == 100)]))
df[(df['Wreck ID'] == 100)] #filters for Wreck ID = 100 ---- note the data type!

<class 'pandas.core.frame.DataFrame'>

   Country  Wreck ID  Strauss ID       Name Parker Number Sea area             Region  Latitude  Longitude  Min depth  Max depth Depth                   Period               Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks Marble type                                        Other cargo Hull remains Shipboard paraphernalia Ship equipment  Estimated tonnage Amphora type
99  Greece       100          79  Kythnos I           NaN   Aegean  Kythnos, Cyclades       NaN        NaN      495.0      495.0  495m  Classical / Hellenistic  2nd half of C4th BC         -350.0       -300.0         NaN                      NaN          NaN          Aegean                    ?  Eleftherotypia 19.10.2004; To Vima 19.10.2004;...  A concentration of amphorae scattered over a 2...      True   False        False       False   False         NaN  Bronze statue of a nude male, partially preser...          NaN                     NaN            NaN                NaN          NaN

In [36]:
df[(df['Country'] == 'Greece') & (df['Period'] == 'Roman Imperial')] #filters for Greece & Roman Imperial

     Country  Wreck ID  Strauss ID                 Name Parker Number               Sea area                               Region  Latitude  Longitude  Min depth  Max depth             Depth          Period                      Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks                                        Marble type                                        Other cargo                                       Hull remains                            Shipboard paraphernalia                                     Ship equipment  Estimated tonnage Amphora type
69    Greece        70          37              Kythera           564                 Aegean      Off southern tip of Peloponnese       NaN        NaN        NaN        NaN            10-15m  Roman Imperial                50 BC-AD 110          -50.0        110.0         NaN                      NaN          NaN          Rhodes                Rome?  Discovered by P. Throckmorton but unpublished,...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
70    Greece        71         309            Methone D           696  Central Mediterranean     South west Messinia, Peloponnese       NaN        NaN        NaN        NaN           Shallow  Roman Imperial              C 2nd -3rd  AD          100.0        300.0         NaN                      NaN          NaN           Assos               Italy?  P. Throckmorton and J. Bullitt, Expedition 5 (...                                                NaN     False    True        False        True   False  Four unfinished garland sarcophagi of Assos st...            Tiles, pottery and a glass unguent jar.                                                NaN                                                NaN         Small water-worn stones, probably ballast.                NaN          NaN
71    Greece        72          39            Piraeus A           817                 Aegean                   In Piraeus harbour       NaN        NaN        NaN        NaN         Not known  Roman Imperial                    C 2nd AD          100.0        200.0         NaN                      NaN          NaN         Aegean?                    ?  G. Bass Archaeology Underwater (1966), 78; Par...                                                NaN     False   False        False       False   False                                                NaN                         Sculptures of the C2nd AD.  Flat bottomed vessel which had burnt and sunk ...                                                NaN                                                NaN                NaN          NaN
72    Greece        73         310            Methone C           695  Central Mediterranean     South west Messinia, Peloponnese       NaN        NaN        NaN        NaN             9-10m  Roman Imperial                  AD 200-250          200.0        250.0         NaN                      NaN          NaN          Aegean               Italy?  P. Throckmorton and J. Bullitt, Expedition 5 (...                                                NaN      True    True         True       False   False  One complete and twenty fragments of already b...                               A fragment of glass.                                                NaN                                                NaN                                                NaN                NaN          NaN
74    Greece        75          43        Antikythera B            45                 Aegean          Off south east Peloponnesus       NaN        NaN        NaN        NaN           Unknown  Roman Imperial            C 1st BC- 5th AD         -100.0        500.0         NaN                      NaN          NaN          Aegean                Rome?       Dumas Trente Siècles sous La Mer (1972), 71.                     Large amphorae ‘like barrels’.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN  Lead stock and reinforcement collar of an anchor.                NaN          NaN
83    Greece        84          64        Makronisi (?)           NaN                 Aegean             Near Leipsoi, Dodecanese       NaN        NaN        NaN        NaN         Not known  Roman Imperial                C 1st-2nd AD            1.0        200.0         NaN                      NaN          NaN          Aegean                    ?  ADelt B Chron 52 (1997), 1188; AR 50 (2003-04)...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
86    Greece        87          61       Astypalaea (?)           NaN                 Aegean               Astypalaea, Dodecanese       NaN        NaN        NaN        NaN               35m  Roman Imperial                    C 3rd AD          200.0        300.0         NaN                      NaN          NaN               ?                    ?  AR 49 (2002-03), 78; www.ekathimerini.com/4dcg...                                                NaN     False   False        False       False   False                                                NaN                 50,000 silver-plated copper coins.                                                NaN                                                NaN                                                NaN                NaN          NaN
91    Greece        92          68             Atalanti            62                 Aegean                                Chios       NaN        NaN        NaN        NaN               22m  Roman Imperial                    C 1st AD            1.0        100.0         NaN                      NaN          NaN          Aegean                    ?  G. Touchais, BCH 109 (1985), 831; Parker (1992...                Amphorae present but not described.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                      A lead anchor _x000D_\nstock.                NaN          NaN
104   Greece       105          83              Paros B           792                 Aegean                      Paros, Cyclades       NaN        NaN        NaN        NaN              5-7m  Roman Imperial                50 BC-AD 150          -50.0        150.0         NaN                      NaN          NaN       Adriatic?                    ?  G. Papathanassopoulos, IJNA 9 (1980), 164-67; ...  A looted and poorly-preserved cargo of amphora...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
105   Greece       106          84              Paros A           791                 Aegean                      Paros, Cyclades       NaN        NaN        NaN        NaN               16m  Roman Imperial                    C 1st AD            1.0        100.0         NaN                      NaN          NaN             Cos                    ?  G. Papathanassopoulos, IJNA 9 (1980), 164-67; ...  A scattered wreck of heavily concreted Coan va...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
106   Greece       107          85      Bay of Paroikia           NaN                 Aegean                      Paros, Cyclades       NaN        NaN        NaN        NaN         Not known  Roman Imperial                    C 2nd AD          100.0        200.0         NaN                      NaN          NaN          Paros?                    ?  E. Hatzidaki and G Papathanassopoulos  IJNA 9 ...                                                NaN     False    True         True       False   False  Two hundred and seven marble objects including...                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
109   Greece       110          38  Agios Petros Bay(?)           NaN                 Aegean                Near Gythion, Laconia       NaN        NaN       15.0       32.0               32m  Roman Imperial      C 1st - early C 2nd AD            1.0        125.0         NaN                      NaN          NaN          Aegean                Rome?                      ADelt 43, AR 41 (1994-5), 14.                   Two amphora types, unidentified.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
192   Greece       193          51             Lindos A           598                 Aegean                               Rhodes       NaN        NaN        NaN        NaN            27-30m  Roman Imperial                50BC- AD 100          -50.0        100.0         NaN                      NaN          NaN          Rhodes                    ?  N. Nikolitsis, Antike Welt 12 (1981), 47-9; Pa...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
193   Greece       194          52            Akandia A            24                 Aegean                               Rhodes       NaN        NaN       36.0       36.0               36m  Roman Imperial  2nd half C 1st BC -C1st AD          -50.0        100.0         NaN                      NaN          NaN          Rhodes                    ?        N. Nikolitsis, Antike Welt 12 (1981), 45-7.  A well-preserved wreck of Roman Rhodian amphor...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
195   Greece       196          56     Syrna Island (?)           NaN                 Aegean                    Syrna, Dodecanese       NaN        NaN        NaN        NaN         Not known  Roman Imperial                    C 2nd AD          100.0        200.0         NaN                      NaN          NaN          Aegean                    ?  www.hcmr.gr/english_site/services/it_app/arche...   'A large number' of amphorae, type not described      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
199   Greece       200          90               Dhia A           359                 Aegean          Island of Dhia, North Crete       NaN        NaN        NaN        NaN               30m  Roman Imperial                    C 1st AD            1.0        100.0         NaN                      NaN          NaN     Rhodes, Cos               Italy?                   Unpublished, Parker (1992), 359.  Main cargo of Rhodian amphorae, also some Nubi...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
201   Greece       202         250               Matala           681  Eastern Mediterranean  North of Bay of Matala, South Crete       NaN        NaN        NaN        NaN                8m  Roman Imperial                50 BC-AD 110          -50.0        110.0         NaN                      NaN          NaN          Crete?                    ?  Grile and C. Davaras (1963), 43-9; Parker (199...  Present but not described apart from what look...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                     Three heaps of ballast stones.                NaN          NaN
202   Greece       203         251          Ayia Galini            68  Eastern Mediterranean      West end of Mesara, south Crete       NaN        NaN        NaN        NaN  5m, by fishermen  Roman Imperial                   AD 276-90          276.0        290.0         NaN                      NaN          NaN          Aegean                Rome?  V. Theophanidis, Arkhaiologike Ephemeris  1949...                                                NaN     False   False        False       False   False                                                NaN  A variety of bronze statue fragments and statu...        A piece of lead, apparently hull sheathing.  Shipboard pottery, and an amphora with a mid-3...                                                NaN                NaN          NaN
1712  Greece      8991           0         Portolafia 1           NaN                    NaN                               Attica   0.00000    0.00000        0.0        0.0               NaN  Roman Imperial                C2nd-C3rd AD          100.0        250.0         0.0                      0.0          0.0             NaN                  NaN  http://chronique.efa.gr/index.php/fiches/voir/...     One of two shipwrecks 'probably from Pontos'?.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                0.0          NaN
1716  Greece      8995           0              Petousi           NaN                    NaN                               Euboia  38.14937   24.16339        0.0        0.0               NaN  Roman Imperial                 C2nd-3rd AD          100.0        250.0         0.0                      0.0          0.0             NaN                  NaN  http://chronique.efa.gr/index.php/fiches/voir/...  A Roman shipwreck was found at this islet outs...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                0.0          NaN

#### What about if we want everything but Greece?

In [37]:
# df[~(df['Country'] == 'Greece')] #filters for not Greece
df[(df['Country'] != 'Greece')] #does the same thing

      Country  Wreck ID  Strauss ID                            Name Parker Number  Sea area                           Region  Latitude  Longitude  Min depth  Max depth    Depth          Period         Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks Marble type                                        Other cargo          Hull remains Shipboard paraphernalia                                     Ship equipment  Estimated tonnage Amphora type
0     Croatia         1         331                          Komiza           NaN  Adriatic                       Vis Island  43.03333   16.08333       30.0       30.0      30m  Roman Imperial    C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN           Egypt       Northern Italy  M. Jurišić, Ancient Shipwrecks of the Adriatic...  Completely looted site with sherds of Egyptian...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                NaN          NaN
1     Croatia         2         328                         Lokunji           NaN  Adriatic                   Kvarner region  44.70000   14.28333        4.0       12.0      12m  Roman Imperial       C 1st AD            1.0        100.0         NaN                      NaN          NaN             Cos       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...                                                NaN      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                NaN          NaN
2     Croatia         3         329                    Maharac Cape           NaN  Adriatic                     Mljet island  42.73333   17.66666        3.0       20.0    3-20m  Roman Imperial       C 1st AD            1.0        100.0         NaN                      NaN          NaN          Rhodes       Northern Italy  D. Vrsalović, PhD thesis (unpublished; 1979), ...                                                NaN      True   False        False       False   False         NaN  Eastern coarse ware pottery of biconical dishe...                   NaN                     NaN                                                NaN                NaN          NaN
3     Croatia         4         330                            Mlin           702  Adriatic                    Split channel  43.45000   16.23333       25.0       40.0      40m  Roman Imperial   C 1st-2nd AD            1.0        200.0         NaN                      NaN          NaN          Aegean       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...  A heavily looted mixed cargo of Greek amphorae...      True   False        False       False   False         NaN                                                NaN  Remains of the hull.                     NaN  Two lead anchor stocks, though possibly not fr...                NaN          NaN
4     Croatia         5         322                        Plavac B           832  Adriatic  Zlarin Island, central Dalmatia       NaN        NaN        NaN        NaN      NaN  Roman Imperial        C1st AD            1.0        100.0         NaN                      NaN          NaN             NaN                  NaN                                                NaN                                                NaN     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                  .                NaN          NaN
...       ...       ...         ...                             ...           ...       ...                              ...       ...        ...        ...        ...      ...             ...            ...            ...          ...         ...                      ...          ...             ...                  ...                                                ...                                                ...       ...     ...          ...         ...     ...         ...                                                ...                   ...                     ...                                                ...                ...          ...
1779    Italy      9058           0              Olbia Late Roman 2           NaN       NaN                         Sardinia  40.91148    9.50738        0.0        0.0       0m      Late Roman        C5th AD          400.0        500.0         0.0                      0.0          0.0             NaN                  NaN  R. D'Oriano, Archeologia in Sardegna, 2007,  9...  Three other C5th AD wrecks found during constr...     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1780    Italy      9059           0                  Olbia medieval           NaN       NaN                         Sardinia  40.91148    9.50738        0.0        0.0       0m        Medieval  C11th-15th AD         1000.0       1500.0         0.0                      0.0          0.0             NaN                  NaN  R. D'Oriano, Archeologia in Sardegna, 2007,  9...  Five small wrecks from the eleventh, fourteent...     False   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1781    Italy      9060           0  Isola della Gallinara (Savona)           NaN       NaN                          Liguria  44.02648    8.22996       50.0       50.0      50m  Roman Republic        C1st BC         -100.0         -1.0         0.0                      0.0          0.0        Campania                  NaN  http://www.archeosub.it/news2003/news0311.htm#...  A mound of intact Dr 1 amphorae and 'other car...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1782    Italy      9061           0                San Vito Lo Capo           NaN       NaN                           Sicily  38.18825   12.74551        0.0        0.0      NaN          Norman       C12th AD         1100.0       1200.0         0.0                      0.0          0.0             NaN                  NaN  F. Faccenna, Il Relitto di San Vito Lo Capo (2...  A local Sicilian ship carrying amphorae and ja...      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN
1783    Italy      9063           0   Capo Colonna and Capo Alfieri           NaN       NaN                         Calabria  38.95399   17.17163        0.0        0.0  shallow      Late Roman    C4th-5th AD          300.0        500.0         0.0                      0.0          0.0             NaN                  NaN  http://www.archeomar.it/templates/archeomar/at...       A probable Late Roman shipwreck of amphorae.      True   False        False       False   False         NaN                                                NaN                   NaN                     NaN                                                NaN                0.0          NaN

[1690 rows x 35 columns]

In [38]:
# gives first 100 wrecks by ID
df[~(df['Wreck ID'] > 100)]

                 Country  Wreck ID  Strauss ID                       Name Parker Number               Sea area                                             Region  Latitude  Longitude  Min depth  Max depth                               Depth                   Period                   Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability             Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks                                        Marble type                                        Other cargo                                       Hull remains                            Shipboard paraphernalia                                     Ship equipment  Estimated tonnage Amphora type
0                Croatia         1         331                     Komiza           NaN               Adriatic                                         Vis Island  43.03333   16.08333       30.0       30.0                                 30m           Roman Imperial              C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN                       Egypt       Northern Italy  M. Jurišić, Ancient Shipwrecks of the Adriatic...  Completely looted site with sherds of Egyptian...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
1                Croatia         2         328                    Lokunji           NaN               Adriatic                                     Kvarner region  44.70000   14.28333        4.0       12.0                                 12m           Roman Imperial                 C 1st AD            1.0        100.0         NaN                      NaN          NaN                         Cos       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
2                Croatia         3         329               Maharac Cape           NaN               Adriatic                                       Mljet island  42.73333   17.66666        3.0       20.0                               3-20m           Roman Imperial                 C 1st AD            1.0        100.0         NaN                      NaN          NaN                      Rhodes       Northern Italy  D. Vrsalović, PhD thesis (unpublished; 1979), ...                                                NaN      True   False        False       False   False                                                NaN  Eastern coarse ware pottery of biconical dishe...                                                NaN                                                NaN                                                NaN                NaN          NaN
3                Croatia         4         330                       Mlin           702               Adriatic                                      Split channel  43.45000   16.23333       25.0       40.0                                 40m           Roman Imperial             C 1st-2nd AD            1.0        200.0         NaN                      NaN          NaN                      Aegean       Northern Italy  D. Vrsalović, Istraživanja i Zaštita Podmorški...  A heavily looted mixed cargo of Greek amphorae...      True   False        False       False   False                                                NaN                                                NaN                               Remains of the hull.                                                NaN  Two lead anchor stocks, though possibly not fr...                NaN          NaN
4                Croatia         5         322                   Plavac B           832               Adriatic                    Zlarin Island, central Dalmatia       NaN        NaN        NaN        NaN                                 NaN           Roman Imperial                  C1st AD            1.0        100.0         NaN                      NaN          NaN                         NaN                  NaN                                                NaN                                                NaN     False   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                  .                NaN          NaN
5                Croatia         6         326                   Tramerka           NaN               Adriatic                                  Northern Dalmatia  44.21666   14.78333       15.0       20.0                                 20m           Roman Imperial                 C 1st AD            1.0        100.0         NaN                      NaN          NaN                      Rhodes       northern Italy  Z. Brusiç, Zbornik Zadarsko otočje 1 (1974), 6...                        A cargo of Rhodian amphorae      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
6                Croatia         7         332               Veliki Skolj           NaN               Adriatic                                       Mljet island  42.70000   17.75000       30.0       31.0                                 31m           Roman Imperial              C1st-2nd AD            1.0        200.0         NaN                      NaN          NaN                      Aegean       Northern Italy  D. Vrsalović, PhD thesis (unpublished, 1979), ...                                                NaN     False    True        False        True   False      15 basins or unfinished sarcophagi with lids.  Sherds of Eastern coarse ware two-handled dish...                                                NaN  A piece of Beltran 2A amphora and some fragmen...                                                NaN                NaN          NaN
7                 France         8         453             La Fourmigue C           425  Western Mediterranean                                    Alpes-Maritimes       NaN        NaN       58.0       58.0                                 58m           Roman Republic             mid C1st  BC          -80.0        -60.0         NaN                      NaN          NaN             Aegean via Cosa               France  DRASM, Archéologie Sous-marine, Arles 83, (198...  A well-preserved tumulus, in spite of looting,...      True   False        False       False   False                                                NaN  A fine collection of furniture and sculptural ...  Proposed length of about 15m capable of carryi...  A stone mortar and pestle of Cycladic marble, ...  Some wooden discs probably belonging to the sh...                NaN          NaN
8                  Italy         9         407             Le Grotticelle           486         Tyrrhenian Sea  Between Ventotene and S. Stefano, Pontine Islands       NaN        NaN       42.0       45.0                              42-45m           Roman Republic              Mid C1st BC          -75.0        -25.0         NaN                      NaN          NaN                     Aegean.                 Rome  M. Cecchini, Sesto Continente 2  (1980), p. 43...  Amphorae of Dr. 1 form marked a much-looted wr...      True   False        False       False   False                                                NaN  About four hundred pieces belonging to couches...                                                NaN  A set of surgical equipment; if 4 probe-like i...                                                NaN                NaN          NaN
9                Croatia        10         323            Koromasna  Cove           NaN               Adriatic                         North side of Zirje island  43.65000   15.65000       35.0       40.0                                 40m           Roman Imperial                 C 1st AD            1.0        100.0         NaN                      NaN          NaN                      Aegean       Northern Italy  J. Mesić, Obavijesti HAD-a XXX1/2 (1999), 76; ...  Intact cargo of Greek amphorae, Cretan AC4 and...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
10                 Italy        11         372                   Ognina A           755  Central Mediterranean                Near Syracuse, east coast of Sicily       NaN        NaN        7.0        8.0                                  8m           Roman Imperial            early C3rd AD          215.0        230.0         NaN                      NaN          NaN  Aegean/N. Africa/Propontis         Sicily/Rome?  G. Käpitan, Recherches sur les Amphores Romain...  'A substantial amphora wreck'.: Mostly African...      True   False        False       False   False                                                NaN                                                NaN  The ship was luxuriously furnished: innumerabl...  Statuettes of bronze (notably a satyr) and blu...  Lead tubing and a group of four bronze pulley ...                NaN          NaN
11                Turkey        12          12         Kizil Burun Column           NaN                 Aegean                                 Southwest of Izmir  38.26075   26.24256       45.0       50.0                                 50m           Roman Republic        Late C 2nd-1st BC         -125.0        -25.0         NaN                      NaN          NaN                 Proconnesus      Claros, Turkey?  http://ina.tamu.edu/kizilburun/index.htm_x000D...  Discovered in 1993 and excavated between 2005 ...      True    True         True       False    True  Eight Proconnesian marble column drums averagi...  Undecorated, utilitarian cookware (plates, cas...  More than 250 fasteners, most of them copper (...  The head of a double axe, an axe-adze, a tool ...  An anchor (in concretion, which with two lead ...                NaN          NaN
12               Croatia        13         337        Vele Orjule/Lussino           NaN               Adriatic                                 Near Losinj Island  44.50000   14.53333       40.0       50.0                                 50m                    Roman          C1st BC- 2nd AD         -110.0        170.0         NaN                      NaN          NaN                      Greece       Northern Italy  M. Jurisić, Ancient Shipwrecks of the Adriatic...  A solitary statue was discovered in several pi...     False   False        False       False   False                                                NaN  A life-size bronze statue of 'Apoxyomenos' was...                                                NaN  A few sherds of Lam. 2 and two solitary Forl. ...  A lead anchor stock nearby and another smaller...                NaN          NaN
13                 Italy        14         362           Mazara del vallo           NaN  Central Mediterranean                Between Sicily and Cap Bon, Tunisia       NaN        NaN      400.0      500.0                                500m           Roman Republic              C3rd-2nd BC         -300.0       -100.0         NaN                      NaN          NaN                      Greece                    ?  http://www.ancientworlds.net/aw/Article/740225...                                 Discovered in 1998      True   False        False       False   False                                                NaN  A bronze satyr was retrieved on two different ...  The remains of the ship were identified by a l...                                                NaN                                                NaN                NaN          NaN
14                Greece        15          72       Aghios Eustratios(?)           NaN                 Aegean                          Between Euboea and Lesbos       NaN        NaN        NaN        NaN                           Not known     early Roman Imperial           End of C1st BC          -25.0         -1.0         NaN                      NaN          NaN                      Aegean                    ?                         National Museum of Athens.                                                NaN     False   False        False       False   False                                                NaN  Bronze statue of Augustus riding a horse.Tthis...                                                NaN                                                NaN                                                NaN                NaN          NaN
15               Lebanon        16         503                     Tyre F          1189  Eastern Mediterranean                          On the south side of Tyre       NaN        NaN        NaN        NaN                             Shallow       Hellenistic/ Roman             C 3rd-2nd BC         -200.0       -100.0         NaN                      NaN          NaN                           ?                    ?  Summary reports, R. Marx, IJNA 3 (1974), 332; ...  Presumably amphorae were found at this looted ...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
16                Turkey        17           1                 Marmaris B           658                 Aegean                                           Marmaris       NaN        NaN        NaN        NaN                           Not known    Classical/Hellenistic    Classical/Hellenistic         -400.0        -25.0         NaN                      NaN          NaN                      Aegean                    ?  G. Kapitän, Tropis 1 (1989),147-62; Parker (19...                                                NaN     False    True        False       False   False  Louteria, similar in shape and concretion to t...                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
17                Turkey        18           2        Kuçük Keramit Adasi           559                 Aegean                                    North of Bodrum       NaN        NaN        NaN        NaN                           Not known    Classical/Hellenistic                 c. 300BC         -310.0       -300.0         NaN                      NaN          NaN                       Samos                    ?  J. Rosloff,  IJNA 10 (1981), 277-86; Parker (1...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
18                Turkey        19           3                Kizil Burun           547                 Aegean                                 Marmaris Peninsula       NaN        NaN        NaN        NaN                                 45m    Classical/Hellenistic               300-250 BC         -300.0       -250.0         NaN                      NaN          NaN                      Rhodes                    ?  J. P. Rosloff, IJNA 10 (1981), 277-86; Parker ...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                         A lagynos.                                                NaN                NaN          NaN
19                Turkey        20           4             Serçe Limani B          1071                 Aegean                                 Marmaris Peninsula       NaN        NaN       35.0       37.0                                 37m              Hellenistic            early C3rd BC         -300.0       -270.0         NaN                      NaN          NaN      Egypt? Datça Peninsula                    ?  G. Bass, IJNA 3 (1974), 335-38; Türk Arkeoloji...  Although many amphorae had been looted before ...      True   False        False       False   False                                                NaN  Minor cargo of small handle-less pots possibly...  Hull timbers with lead sheathing; woven fabric...  It is  known that the ship sank in early summe...        Lead piping, lead rings and wooden toggles.                NaN          NaN
20                Turkey        21           5            Mandalya Gulf B           643                 Aegean                                    North of Bodrum       NaN        NaN        NaN        NaN                             Shallow        Hellenistic/Roman             C 3rd-2nd BC         -300.0       -100.0         NaN                      NaN          NaN                      Aegean                    ?  G. Bass, Anatolian Studies 36 (1986), 214-16; ...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
21                Turkey        22           7             Serçe Limani C          1072                 Aegean                                 Marmaris Peninsula       NaN        NaN        NaN        NaN                           Not known        Hellenistic/Roman               150-100 BC         -150.0       -100.0         NaN                      NaN          NaN            Palestine/Rhodes                    ?  G. Bass, II Kazi Sonuçlari Toplantisi Ankara (...                                                NaN      True   False        False       False   False                                                NaN                               Palestinian pottery.                                                NaN                                                NaN                                                NaN                NaN          NaN

#### Combine two filters with `&` = `and`

In [39]:
df[(df['Country'] == 'Greece') & (df['Period'] == 'Roman Imperial')] #filters for Greece & Roman Imperial

     Country  Wreck ID  Strauss ID                 Name Parker Number               Sea area                               Region  Latitude  Longitude  Min depth  Max depth             Depth          Period                      Dating  Earliest date  Latest date  Date range  Mid point of date range  Probability Place of origin Place of destination                                          Reference                                           Comments  Amphorae  Marble  Columns etc  Sarcophagi  Blocks                                        Marble type                                        Other cargo                                       Hull remains                            Shipboard paraphernalia                                     Ship equipment  Estimated tonnage Amphora type
69    Greece        70          37              Kythera           564                 Aegean      Off southern tip of Peloponnese       NaN        NaN        NaN        NaN            10-15m  Roman Imperial                50 BC-AD 110          -50.0        110.0         NaN                      NaN          NaN          Rhodes                Rome?  Discovered by P. Throckmorton but unpublished,...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
70    Greece        71         309            Methone D           696  Central Mediterranean     South west Messinia, Peloponnese       NaN        NaN        NaN        NaN           Shallow  Roman Imperial              C 2nd -3rd  AD          100.0        300.0         NaN                      NaN          NaN           Assos               Italy?  P. Throckmorton and J. Bullitt, Expedition 5 (...                                                NaN     False    True        False        True   False  Four unfinished garland sarcophagi of Assos st...            Tiles, pottery and a glass unguent jar.                                                NaN                                                NaN         Small water-worn stones, probably ballast.                NaN          NaN
71    Greece        72          39            Piraeus A           817                 Aegean                   In Piraeus harbour       NaN        NaN        NaN        NaN         Not known  Roman Imperial                    C 2nd AD          100.0        200.0         NaN                      NaN          NaN         Aegean?                    ?  G. Bass Archaeology Underwater (1966), 78; Par...                                                NaN     False   False        False       False   False                                                NaN                         Sculptures of the C2nd AD.  Flat bottomed vessel which had burnt and sunk ...                                                NaN                                                NaN                NaN          NaN
72    Greece        73         310            Methone C           695  Central Mediterranean     South west Messinia, Peloponnese       NaN        NaN        NaN        NaN             9-10m  Roman Imperial                  AD 200-250          200.0        250.0         NaN                      NaN          NaN          Aegean               Italy?  P. Throckmorton and J. Bullitt, Expedition 5 (...                                                NaN      True    True         True       False   False  One complete and twenty fragments of already b...                               A fragment of glass.                                                NaN                                                NaN                                                NaN                NaN          NaN
74    Greece        75          43        Antikythera B            45                 Aegean          Off south east Peloponnesus       NaN        NaN        NaN        NaN           Unknown  Roman Imperial            C 1st BC- 5th AD         -100.0        500.0         NaN                      NaN          NaN          Aegean                Rome?       Dumas Trente Siècles sous La Mer (1972), 71.                     Large amphorae ‘like barrels’.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN  Lead stock and reinforcement collar of an anchor.                NaN          NaN
83    Greece        84          64        Makronisi (?)           NaN                 Aegean             Near Leipsoi, Dodecanese       NaN        NaN        NaN        NaN         Not known  Roman Imperial                C 1st-2nd AD            1.0        200.0         NaN                      NaN          NaN          Aegean                    ?  ADelt B Chron 52 (1997), 1188; AR 50 (2003-04)...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
86    Greece        87          61       Astypalaea (?)           NaN                 Aegean               Astypalaea, Dodecanese       NaN        NaN        NaN        NaN               35m  Roman Imperial                    C 3rd AD          200.0        300.0         NaN                      NaN          NaN               ?                    ?  AR 49 (2002-03), 78; www.ekathimerini.com/4dcg...                                                NaN     False   False        False       False   False                                                NaN                 50,000 silver-plated copper coins.                                                NaN                                                NaN                                                NaN                NaN          NaN
91    Greece        92          68             Atalanti            62                 Aegean                                Chios       NaN        NaN        NaN        NaN               22m  Roman Imperial                    C 1st AD            1.0        100.0         NaN                      NaN          NaN          Aegean                    ?  G. Touchais, BCH 109 (1985), 831; Parker (1992...                Amphorae present but not described.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                      A lead anchor _x000D_\nstock.                NaN          NaN
104   Greece       105          83              Paros B           792                 Aegean                      Paros, Cyclades       NaN        NaN        NaN        NaN              5-7m  Roman Imperial                50 BC-AD 150          -50.0        150.0         NaN                      NaN          NaN       Adriatic?                    ?  G. Papathanassopoulos, IJNA 9 (1980), 164-67; ...  A looted and poorly-preserved cargo of amphora...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
105   Greece       106          84              Paros A           791                 Aegean                      Paros, Cyclades       NaN        NaN        NaN        NaN               16m  Roman Imperial                    C 1st AD            1.0        100.0         NaN                      NaN          NaN             Cos                    ?  G. Papathanassopoulos, IJNA 9 (1980), 164-67; ...  A scattered wreck of heavily concreted Coan va...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
106   Greece       107          85      Bay of Paroikia           NaN                 Aegean                      Paros, Cyclades       NaN        NaN        NaN        NaN         Not known  Roman Imperial                    C 2nd AD          100.0        200.0         NaN                      NaN          NaN          Paros?                    ?  E. Hatzidaki and G Papathanassopoulos  IJNA 9 ...                                                NaN     False    True         True       False   False  Two hundred and seven marble objects including...                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
109   Greece       110          38  Agios Petros Bay(?)           NaN                 Aegean                Near Gythion, Laconia       NaN        NaN       15.0       32.0               32m  Roman Imperial      C 1st - early C 2nd AD            1.0        125.0         NaN                      NaN          NaN          Aegean                Rome?                      ADelt 43, AR 41 (1994-5), 14.                   Two amphora types, unidentified.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
192   Greece       193          51             Lindos A           598                 Aegean                               Rhodes       NaN        NaN        NaN        NaN            27-30m  Roman Imperial                50BC- AD 100          -50.0        100.0         NaN                      NaN          NaN          Rhodes                    ?  N. Nikolitsis, Antike Welt 12 (1981), 47-9; Pa...                                                NaN      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
193   Greece       194          52            Akandia A            24                 Aegean                               Rhodes       NaN        NaN       36.0       36.0               36m  Roman Imperial  2nd half C 1st BC -C1st AD          -50.0        100.0         NaN                      NaN          NaN          Rhodes                    ?        N. Nikolitsis, Antike Welt 12 (1981), 45-7.  A well-preserved wreck of Roman Rhodian amphor...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
195   Greece       196          56     Syrna Island (?)           NaN                 Aegean                    Syrna, Dodecanese       NaN        NaN        NaN        NaN         Not known  Roman Imperial                    C 2nd AD          100.0        200.0         NaN                      NaN          NaN          Aegean                    ?  www.hcmr.gr/english_site/services/it_app/arche...   'A large number' of amphorae, type not described      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
199   Greece       200          90               Dhia A           359                 Aegean          Island of Dhia, North Crete       NaN        NaN        NaN        NaN               30m  Roman Imperial                    C 1st AD            1.0        100.0         NaN                      NaN          NaN     Rhodes, Cos               Italy?                   Unpublished, Parker (1992), 359.  Main cargo of Rhodian amphorae, also some Nubi...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                NaN          NaN
201   Greece       202         250               Matala           681  Eastern Mediterranean  North of Bay of Matala, South Crete       NaN        NaN        NaN        NaN                8m  Roman Imperial                50 BC-AD 110          -50.0        110.0         NaN                      NaN          NaN          Crete?                    ?  Grile and C. Davaras (1963), 43-9; Parker (199...  Present but not described apart from what look...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                     Three heaps of ballast stones.                NaN          NaN
202   Greece       203         251          Ayia Galini            68  Eastern Mediterranean      West end of Mesara, south Crete       NaN        NaN        NaN        NaN  5m, by fishermen  Roman Imperial                   AD 276-90          276.0        290.0         NaN                      NaN          NaN          Aegean                Rome?  V. Theophanidis, Arkhaiologike Ephemeris  1949...                                                NaN     False   False        False       False   False                                                NaN  A variety of bronze statue fragments and statu...        A piece of lead, apparently hull sheathing.  Shipboard pottery, and an amphora with a mid-3...                                                NaN                NaN          NaN
1712  Greece      8991           0         Portolafia 1           NaN                    NaN                               Attica   0.00000    0.00000        0.0        0.0               NaN  Roman Imperial                C2nd-C3rd AD          100.0        250.0         0.0                      0.0          0.0             NaN                  NaN  http://chronique.efa.gr/index.php/fiches/voir/...     One of two shipwrecks 'probably from Pontos'?.      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                0.0          NaN
1716  Greece      8995           0              Petousi           NaN                    NaN                               Euboia  38.14937   24.16339        0.0        0.0               NaN  Roman Imperial                 C2nd-3rd AD          100.0        250.0         0.0                      0.0          0.0             NaN                  NaN  http://chronique.efa.gr/index.php/fiches/voir/...  A Roman shipwreck was found at this islet outs...      True   False        False       False   False                                                NaN                                                NaN                                                NaN                                                NaN                                                NaN                0.0          NaN

#### Combine two filters with `|` = `or`

In [40]:
# df[(df['Country'] == 'Greece') | (df['Country'] == 'Italy')] #filters for Greece or Italy
# crashes the notebook for some reason