Write a SPARQL query to receive all Athenian writers of fifth-century BCE.

In [22]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 3)

In [32]:
sparql = SPARQLWrapper("https://query.wikidata.org/sparql")

In [81]:
sparql.setQuery("""
SELECT ?writer ?writerLabel

WHERE {
    ?writer wdt:P31 wd:Q5 .         # instance of human (is human)
    ?writer wdt:P106 wd:Q36180 .    # occuipation writer  
    ?writer wdt:P27 wd:Q844930 .      # country of citizenship, classical athens
    ?writer wdt:P569 ?dtb .         # lived in fifth century - dob before -400
        FILTER(YEAR(?dtb) < -400) 
    ?writer wdt:P570 ?dtd .         # lived in fifth century - dod after -499
        FILTER(YEAR(?dtd) > -499)
    

    
    
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}


""")
sparql.setReturnFormat(JSON)
results = sparql.query().convert()
results_df = pd.json_normalize(results['results']['bindings']) #this converts from an JSON to a dataframe, using the info we want
results_df = results_df[['writer.value','writerLabel.value']] #this filters the dataframe to only show the columns we want
results_df.drop_duplicates()

                               writer.value writerLabel.value
0   http://www.wikidata.org/entity/Q1627567       Pherecrates
1    http://www.wikidata.org/entity/Q459517           Eupolis
2    http://www.wikidata.org/entity/Q537647       Onomacritus
3    http://www.wikidata.org/entity/Q732715        Polycrates
4   http://www.wikidata.org/entity/Q2973270          Cinesias
5       http://www.wikidata.org/entity/Q859             Plato
8       http://www.wikidata.org/entity/Q913          Socrates
9      http://www.wikidata.org/entity/Q7235         Sophocles
10    http://www.wikidata.org/entity/Q41683        Thucydides
11    http://www.wikidata.org/entity/Q48305         Euripides
12   http://www.wikidata.org/entity/Q129772          Xenophon
13   http://www.wikidata.org/entity/Q162163      Ion of Chios
14   http://www.wikidata.org/entity/Q221182         Isocrates
15   http://www.wikidata.org/entity/Q294092           Critias
16   http://www.wikidata.org/entity/Q380482           Agathon

In [82]:
# # sets a variable for occupation and gets writers OR orators
# sparql.setQuery("""

# SELECT ?item ?itemLabel 
# WHERE 
# {
#   ?item wdt:P31 wd:Q5 .            #instance human
#   ?item wdt:P106 ?occupation       # gives writer or orator
#         FILTER(?occupation  IN(wd:Q36180, wd:Q12859263) ) . 
#   ?item wdt:P569 ?dtb.             #variables and filters for birthdate, deathdate
#       FILTER(YEAR(?dtb) < -400) 
#   ?item wdt:P570 ?dtd .
#       FILTER(YEAR(?dtd) > -499)
#   ?item wdt:P19 wd:Q1524            #birthplace athens
  
  
#   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } # Helps get the label in your language, if not, then en language
  
# }
# """)
# sparql.setReturnFormat(JSON)
# results = sparql.query().convert()
# results

# Wikidata code finder

In [54]:
import requests

def search_entities(search_string, entity_type, language='en'):
    endpoint_url = "https://www.wikidata.org/w/api.php"

    # Define the parameters for the API call
    params = {
        'action': 'wbsearchentities',
        'format': 'json',
        'search': search_string,
        'type': entity_type,
        'language': language   
    }

    # Make the API call
    response = requests.get(endpoint_url, params=params)
    data = response.json()

    # Extract and return entity IDs and labels
    entities = data.get('search', [])
    return entities

def display_entities(entities, entity_type):
    print(f"\n{entity_type.capitalize()}:")
    for entity in entities:
        print(f"Entity ID: {entity['id']} - Label: {entity['label']} - Description: {entity['display']['description']['value']} - {entity['concepturi']}")

if __name__ == "__main__":
    search_string = input("Enter the string to search for: ")
    
    # Search for items
    items = search_entities(search_string, 'item')
    display_entities(items, 'items')

    # Search for properties
    properties = search_entities(search_string, 'property')
    display_entities(properties, 'properties')

Enter the string to search for: greece

Items:
Entity ID: Q41 - Label: Greece - Description: country in Southeast Europe - http://www.wikidata.org/entity/Q41
Entity ID: Q11772 - Label: Ancient Greece - Description: Greek civilization from c. 1200 BC to c. 600 AD - http://www.wikidata.org/entity/Q11772
Entity ID: Q17077105 - Label: Greece - Description: constituency of the European Parliament - http://www.wikidata.org/entity/Q17077105
Entity ID: Q265824 - Label: Second Hellenic Republic - Description: former country (1924-1935) - http://www.wikidata.org/entity/Q265824
Entity ID: Q2610369 - Label: Greece - Description: town in New York, United States - http://www.wikidata.org/entity/Q2610369
Entity ID: Q1358836 - Label: 4th of August Regime - Description: military dictatorship of Greece from 1936 to 1941 - http://www.wikidata.org/entity/Q1358836
Entity ID: Q36902901 - Label: Greece - Description: family name - http://www.wikidata.org/entity/Q36902901

Properties: